// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetAI.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NetAI.Api.Migrations
{
    [DbContext(typeof(NetAiDbContext))]
    partial class NetAiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NetAI.Api.Data.Entities.Conversations.ConversationEventRecord", b =>
                {
                    b.Property<Guid>("ConversationMetadataRecordId")
                        .HasColumnType("uuid");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("ConversationMetadataRecordId", "EventId");

                    b.ToTable("ConversationEvents", (string)null);
                });

            modelBuilder.Entity("NetAI.Api.Data.Entities.Conversations.ConversationFeedbackRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversationMetadataRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeedbackJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConversationMetadataRecordId");

                    b.ToTable("ConversationFeedbackEntries", (string)null);
                });

            modelBuilder.Entity("NetAI.Api.Data.Entities.Conversations.ConversationFileRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversationMetadataRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationMetadataRecordId", "Path")
                        .IsUnique();

                    b.ToTable("ConversationFiles", (string)null);
                });

            modelBuilder.Entity("NetAI.Api.Data.Entities.Conversations.ConversationGitDiffRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversationMetadataRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Modified")
                        .HasColumnType("text");

                    b.Property<string>("Original")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationMetadataRecordId", "Path")
                        .IsUnique();

                    b.ToTable("ConversationGitDiffs", (string)null);
                });

            modelBuilder.Entity("NetAI.Api.Data.Entities.Conversations.ConversationMicroagentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationMetadataRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("InputsJson")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ToolsJson")
                        .HasColumnType("text");

                    b.Property<string>("TriggersJson")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationMetadataRecordId", "Name")
                        .IsUnique();

                    b.ToTable("ConversationMicroagents", (string)null);
                });

            modelBuilder.Entity("NetAI.Api.Data.Entities.Conversations.ConversationRememberPromptRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversationMetadataRecordId")
                        .HasColumnType("uuid");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("Prompt")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConversationMetadataRecordId", "EventId")
                        .IsUnique();

                    b.ToTable("ConversationRememberPrompts", (string)null);
                });

            modelBuilder.Entity("NetAI.Api.Data.Entities.OpenHands.EventCallbackRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasColumnName("created_at");

                    b.Property<string>("EventKind")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_kind");

                    b.Property<string>("ProcessorJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("processor");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_event_callback_created_at");

                    b.ToTable("event_callback", (string)null);
                });

            modelBuilder.Entity("NetAI.Api.Data.Entities.OpenHands.EventCallbackResultRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("detail");

                    b.Property<Guid>("EventCallbackId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_callback_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_event_callback_result_conversation_id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_event_callback_result_created_at");

                    b.HasIndex("EventCallbackId")
                        .HasDatabaseName("ix_event_callback_result_event_callback_id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_event_callback_result_event_id");

                    b.ToTable("event_callback_result", (string)null);
                });

            modelBuilder.Entity("NetAI.Api.Data.Entities.Conversations.ConversationRuntimeHostRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversationRuntimeInstanceRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Url")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationRuntimeInstanceRecordId", "Name")
                        .IsUnique();

                    b.ToTable("ConversationRuntimeHosts", (string)null);
                });

            modelBuilder.Entity("NetAI.Api.Data.Entities.Conversations.ConversationRuntimeInstanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversationMetadataRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("RuntimeId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RuntimeStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SessionApiKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VscodeUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationMetadataRecordId")
                        .IsUnique();

                    b.ToTable("ConversationRuntimeInstances", (string)null);
                });

            modelBuilder.Entity("NetAI.Api.Data.Entities.Conversations.ConversationRuntimeProviderRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversationRuntimeInstanceRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationRuntimeInstanceRecordId", "Provider")
                        .IsUnique();

                    b.ToTable("ConversationRuntimeProviders", (string)null);
                });

            modelBuilder.Entity("NetAI.Api.Data.Entities.OpenHands.ConversationMetadataRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AccumulatedCost")
                        .HasColumnType("double precision");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("integer");

                    b.Property<string>("ConversationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ConversationVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("GitProvider")
                        .HasColumnType("text");

                    b.Property<string>("GitProviderRaw")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("LastUpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LlmModel")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("integer");

                    b.Property<string>("PullRequestNumbers")
                        .HasColumnType("text");

                    b.Property<string>("RuntimeId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RuntimeStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SandboxId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SelectedBranch")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SelectedRepository")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("SessionApiKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Trigger")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("VscodeUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId")
                        .IsUnique();

                    b.ToTable("ConversationMetadata", (string)null);
                });

            modelBuilder.Entity("NetAI.Api.Data.Entities.OpenHands.ConversationStartTaskRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentServerUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("AppConversationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BackendError")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConversationStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Detail")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("FailureDetail")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("RequestJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}")
                        .HasColumnName("Request");

                    b.Property<string>("RuntimeStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SandboxId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SandboxSessionApiKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SandboxVscodeUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("SandboxWorkspacePath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("AppConversationId");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("ConversationStartTasks", (string)null);
                });

            modelBuilder.Entity("NetAI.Api.Data.Entities.Sandboxes.SandboxRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ExposedUrlsJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]")
                        .HasColumnName("ExposedUrls");

                    b.Property<DateTimeOffset>("LastUpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("RuntimeHostsJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]")
                        .HasColumnName("RuntimeHosts");

                    b.Property<string>("RuntimeId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RuntimeStateJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}")
                        .HasColumnName("RuntimeState");

                    b.Property<string>("RuntimeUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("SandboxSpecId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SessionApiKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WorkspacePath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("SandboxSpecId");

                    b.ToTable("Sandboxes", (string)null);
                });

            modelBuilder.Entity("NetAI.Api.Data.Entities.Sandboxes.SandboxSpecRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CommandJson")
                        .HasColumnType("text")
                        .HasColumnName("Command");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("InitialEnvJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}")
                        .HasColumnName("InitialEnv");

                    b.Property<string>("WorkingDir")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasDefaultValue("/home/openhands/workspace");

                    b.HasKey("Id");

                    b.ToTable("SandboxSpecs", (string)null);
                });

            modelBuilder.Entity("NetAI.Api.Data.Entities.Conversations.ConversationEventRecord", b =>
                {
                    b.HasOne("NetAI.Api.Data.Entities.OpenHands.ConversationMetadataRecord", "Conversation")
                        .WithMany("Events")
                        .HasForeignKey("ConversationMetadataRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("NetAI.Api.Data.Entities.Conversations.ConversationFeedbackRecord", b =>
                {
                    b.HasOne("NetAI.Api.Data.Entities.OpenHands.ConversationMetadataRecord", "Conversation")
                        .WithMany("FeedbackEntries")
                        .HasForeignKey("ConversationMetadataRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("NetAI.Api.Data.Entities.Conversations.ConversationFileRecord", b =>
                {
                    b.HasOne("NetAI.Api.Data.Entities.OpenHands.ConversationMetadataRecord", "Conversation")
                        .WithMany("Files")
                        .HasForeignKey("ConversationMetadataRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("NetAI.Api.Data.Entities.Conversations.ConversationGitDiffRecord", b =>
                {
                    b.HasOne("NetAI.Api.Data.Entities.OpenHands.ConversationMetadataRecord", "Conversation")
                        .WithMany("GitDiffs")
                        .HasForeignKey("ConversationMetadataRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("NetAI.Api.Data.Entities.Conversations.ConversationMicroagentRecord", b =>
                {
                    b.HasOne("NetAI.Api.Data.Entities.OpenHands.ConversationMetadataRecord", "Conversation")
                        .WithMany("Microagents")
                        .HasForeignKey("ConversationMetadataRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("NetAI.Api.Data.Entities.Conversations.ConversationRememberPromptRecord", b =>
                {
                    b.HasOne("NetAI.Api.Data.Entities.OpenHands.ConversationMetadataRecord", "Conversation")
                        .WithMany("RememberPrompts")
                        .HasForeignKey("ConversationMetadataRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("NetAI.Api.Data.Entities.Conversations.ConversationRuntimeHostRecord", b =>
                {
                    b.HasOne("NetAI.Api.Data.Entities.Conversations.ConversationRuntimeInstanceRecord", "RuntimeInstance")
                        .WithMany("Hosts")
                        .HasForeignKey("ConversationRuntimeInstanceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RuntimeInstance");
                });

            modelBuilder.Entity("NetAI.Api.Data.Entities.Conversations.ConversationRuntimeInstanceRecord", b =>
                {
                    b.HasOne("NetAI.Api.Data.Entities.OpenHands.ConversationMetadataRecord", "Conversation")
                        .WithOne("RuntimeInstance")
                        .HasForeignKey("NetAI.Api.Data.Entities.Conversations.ConversationRuntimeInstanceRecord", "ConversationMetadataRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("NetAI.Api.Data.Entities.Conversations.ConversationRuntimeProviderRecord", b =>
                {
                    b.HasOne("NetAI.Api.Data.Entities.Conversations.ConversationRuntimeInstanceRecord", "RuntimeInstance")
                        .WithMany("Providers")
                        .HasForeignKey("ConversationRuntimeInstanceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RuntimeInstance");
                });

            modelBuilder.Entity("NetAI.Api.Data.Entities.Sandboxes.SandboxRecord", b =>
                {
                    b.HasOne("NetAI.Api.Data.Entities.Sandboxes.SandboxSpecRecord", null)
                        .WithMany()
                        .HasForeignKey("SandboxSpecId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NetAI.Api.Data.Entities.OpenHands.EventCallbackResultRecord", b =>
                {
                    b.HasOne("NetAI.Api.Data.Entities.OpenHands.EventCallbackRecord", "EventCallback")
                        .WithMany("Results")
                        .HasForeignKey("EventCallbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventCallback");
                });

            modelBuilder.Entity("NetAI.Api.Data.Entities.Conversations.ConversationRuntimeInstanceRecord", b =>
                {
                    b.Navigation("Hosts");

                    b.Navigation("Providers");
                });

            modelBuilder.Entity("NetAI.Api.Data.Entities.OpenHands.ConversationMetadataRecord", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("FeedbackEntries");

                    b.Navigation("Files");

                    b.Navigation("GitDiffs");

                    b.Navigation("Microagents");

                    b.Navigation("RememberPrompts");

                    b.Navigation("RuntimeInstance");
                });

            modelBuilder.Entity("NetAI.Api.Data.Entities.OpenHands.EventCallbackRecord", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
